#!/bin/bash
# ==============================================================================
# EugineBill All-in-One Automated VPS Installer
# Usage: sudo bash scripts/install.sh
# Description: Fully automated single-command setup for fresh Ubuntu/Debian VPS.
#              Installs Node.js 20, MySQL, PM2, WireGuard, Socat, configures .env,
#              sets up persistent storage, pushes database schema, builds app,
#              and launches the First-Time Web Setup Wizard.
# ==============================================================================

set -e

COLOR_RESET="\033[0m"
COLOR_INFO="\033[36m"
COLOR_SUCCESS="\033[32m"
COLOR_WARN="\033[33m"
COLOR_ERROR="\033[31m"
COLOR_BOLD="\033[1m"

log_info() { echo -e "${COLOR_INFO}[INFO]${COLOR_RESET} $1"; }
log_success() { echo -e "${COLOR_SUCCESS}[OK]${COLOR_RESET} $1"; }
log_warn() { echo -e "${COLOR_WARN}[WARN]${COLOR_RESET} $1"; }
log_error() { echo -e "${COLOR_ERROR}[ERROR]${COLOR_RESET} $1"; }

# 1. Root Check
if [ "$EUID" -ne 0 ]; then
    log_error "Skrip ini harus dijalankan dengan hak akses root (sudo)."
    echo "Contoh: sudo bash scripts/install.sh"
    exit 1
fi

echo -e "${COLOR_INFO}${COLOR_BOLD}"
echo "================================================================="
echo "        EUGINEBILL ALL-IN-ONE AUTOMATED VPS INSTALLER            "
echo "              Managed Single-Tenant VPS Setup                    "
echo "================================================================="
echo -e "${COLOR_RESET}"

# 2. Path Setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_DIR}"

log_info "Direktori project: ${PROJECT_DIR}"

# 3. Auto-Detect Public IP
DETECTED_IP=$(curl -s4 --max-time 3 ifconfig.me || curl -s4 --max-time 3 icanhazip.com || echo "127.0.0.1")
log_info "IP Publik terdeteksi: ${DETECTED_IP}"

echo ""
echo -e "${COLOR_BOLD}Konfigurasi Cepat (Tekan ENTER untuk memilih nilai default):${COLOR_RESET}"

read -p "1. Domain atau IP Publik VPS [Default: ${DETECTED_IP}]: " INPUT_HOST
SERVER_HOST="${INPUT_HOST:-$DETECTED_IP}"

# Format APP_URL (jika domain gunakan https/http, jika IP gunakan port 3000)
if [[ "${SERVER_HOST}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    DEFAULT_APP_URL="http://${SERVER_HOST}:3000"
else
    DEFAULT_APP_URL="https://${SERVER_HOST}"
fi

read -p "2. App URL untuk pelanggan [Default: ${DEFAULT_APP_URL}]: " INPUT_URL
APP_URL="${INPUT_URL:-$DEFAULT_APP_URL}"

# Generate random secure DB password
GEN_DB_PASS=$(openssl rand -hex 12)
read -p "3. Password Database MySQL [Default: ${GEN_DB_PASS}]: " INPUT_DB_PASS
DB_PASS="${INPUT_DB_PASS:-$GEN_DB_PASS}"

echo ""
log_info "Menjalankan instalasi sistem otomatis..."

# 4. System Updates & Dependencies
log_info "Memperbarui paket sistem dan menginstal dependensi dasar..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git ufw socat mysql-server wireguard gzip openssl build-essential

# 5. Node.js 20 LTS Installation
if ! command -v node >/dev/null 2>&1 || [[ $(node -v) != v20* ]]; then
    log_info "Menginstal Node.js 20.x LTS..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
fi
log_success "Node.js $(node -v) & npm $(npm -v) siap."

# 6. PM2 Global Installation
if ! command -v pm2 >/dev/null 2>&1; then
    log_info "Menginstal PM2 process manager..."
    npm install -g pm2
fi
log_success "PM2 siap."

# 7. Setup MySQL Database
log_info "Mengonfigurasi database MySQL 'euginebill'..."
systemctl start mysql || service mysql start

mysql -u root <<EOF
CREATE DATABASE IF NOT EXISTS euginebill CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'eugineuser'@'localhost' IDENTIFIED BY '${DB_PASS}';
ALTER USER 'eugineuser'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON euginebill.* TO 'eugineuser'@'localhost';
FLUSH PRIVILEGES;
EOF
log_success "Database 'euginebill' dan user 'eugineuser' berhasil dikonfigurasi."

# 8. Setup Persistent Upload Directory
UPLOAD_DIR="/var/data/EugineBill/uploads"
log_info "Menyiapkan direktori penyimpanan file persisten di: ${UPLOAD_DIR}"
mkdir -p "${UPLOAD_DIR}/receipts"
mkdir -p "${UPLOAD_DIR}/proofs"
mkdir -p "${UPLOAD_DIR}/logos"
mkdir -p "${UPLOAD_DIR}/customers"
chmod -R 775 /var/data/EugineBill
log_success "Direktori penyimpanan persisten siap."

# 9. Generate Secret Keys & Write .env
log_info "Menghasilkan kunci keamanan enkripsi dan menulis file .env..."
NEXTAUTH_SEC=$(openssl rand -base64 32)
AGENT_JWT_SEC=$(openssl rand -base64 32)
TECH_JWT_SEC=$(openssl rand -base64 32)
ENC_KEY=$(openssl rand -hex 16)

cat > .env <<EOF
# Auto-generated by EugineBill Installer on $(date)
DATABASE_URL="mysql://eugineuser:${DB_PASS}@localhost:3306/euginebill?connection_limit=10&pool_timeout=20"

TZ="Asia/Jakarta"
NEXT_PUBLIC_TIMEZONE="Asia/Jakarta"

NEXT_PUBLIC_APP_NAME="EugineBill"
NEXT_PUBLIC_APP_URL="${APP_URL}"

VPS_PUBLIC_IP="${SERVER_HOST}"
RADIUS_SERVER_IP="${SERVER_HOST}"

UPLOAD_DIR="${UPLOAD_DIR}"

NEXTAUTH_SECRET="${NEXTAUTH_SEC}"
NEXTAUTH_URL="${APP_URL}"
AGENT_JWT_SECRET="${AGENT_JWT_SEC}"
TECHNICIAN_JWT_SECRET="${TECH_JWT_SEC}"
ENCRYPTION_KEY="${ENC_KEY}"
EOF
log_success "File .env berhasil dibuat dengan kunci keamanan unik."

# 10. Install NPM Dependencies & Sync Schema
log_info "Menginstal modul npm dan membangun Prisma Client..."
npm install --prefer-offline --no-audit

log_info "Sinkronisasi skema tabel database..."
npx prisma generate
npx prisma db push --skip-generate
log_success "Skema database berhasil disinkronkan."

# 11. Configure Firewall Ports
if [ -f "scripts/setup-vps-ports.sh" ]; then
    log_info "Membuka seluruh port firewall yang dibutuhkan..."
    bash scripts/setup-vps-ports.sh
fi

# 12. Build Production
log_info "Membangun Next.js production build..."
npm run build
log_success "Build aplikasi selesai."

# 13. Start with PM2
log_info "Menjalankan aplikasi dengan PM2..."
pm2 delete "EugineBill-radius" >/dev/null 2>&1 || true
pm2 start npm --name "EugineBill-radius" -- start
pm2 save
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true

# 14. Finished Banner
echo ""
echo -e "${COLOR_SUCCESS}${COLOR_BOLD}"
echo "================================================================="
echo "             INSTALASI EUGINEBILL BERHASIL SELESAI!              "
echo "================================================================="
echo -e "${COLOR_RESET}"
echo -e "Aplikasi sekarang sedang berjalan di latar belakang (PM2)."
echo ""
echo -e "Silakan buka browser Anda untuk menyelesaikan Setup Wizard:"
echo -e "👉 ${COLOR_BOLD}${COLOR_INFO}${APP_URL}/setup${COLOR_RESET}"
if [ "${APP_URL}" != "http://${SERVER_HOST}:3000" ]; then
    echo -e "   (Atau alternatif IP: http://${SERVER_HOST}:3000/setup)"
fi
echo ""
echo -e "Kredensial Database MySQL yang disimpan di .env:"
echo -e "   User:     ${COLOR_BOLD}eugineuser${COLOR_RESET}"
echo -e "   Database: ${COLOR_BOLD}euginebill${COLOR_RESET}"
echo -e "   Password: ${COLOR_BOLD}${DB_PASS}${COLOR_RESET}"
echo ""
echo -e "${COLOR_SUCCESS}Langkah berikutnya: Buka link di atas pada browser, isi Profil ISP dan buat akun Superadmin.${COLOR_RESET}"
echo "================================================================="
