import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 1. Standard Master Items conforming to EMG-[KATEGORI]-[SUB-KATEGORI]-[DETAIL/VARIAN]
const MASTER_ITEMS = [
  // ─── CPE: Modem & Customer Equipment (isSerialized: true) ─────────────
  {
    sku: 'EMG-CPE-ONT-ZTE-F609V3',
    name: 'Modem ZTE F609 V3 Gigabit',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 150000,
    sellingPrice: 250000,
    minimumStock: 10,
  },
  {
    sku: 'EMG-CPE-ONT-SKW-542VF',
    name: 'Modem Skyworth GN542VF Dual Band',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 165000,
    sellingPrice: 275000,
    minimumStock: 10,
  },
  {
    sku: 'EMG-CPE-ONT-RLT-OEM',
    name: 'Modem Realtek / ZTE OEM GPON',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 140000,
    sellingPrice: 230000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-YHT-100G',
    name: 'Modem Yuhua 100G GPON',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 135000,
    sellingPrice: 220000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-FBH-HG6243',
    name: 'Modem FiberHome HG6243C GPON',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 155000,
    sellingPrice: 250000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-HWA-8245H',
    name: 'Modem Huawei EchoLife HG8245H',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 160000,
    sellingPrice: 260000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-GGL-FD511G',
    name: 'Modem Gigalink / C-Data FD511G',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 130000,
    sellingPrice: 210000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-VSL-V2801',
    name: 'Modem VSOL V2801 Series',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 140000,
    sellingPrice: 230000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CPE-ONT-EFT-OEM',
    name: 'Modem EFiber OEM GPON',
    categoryCode: 'CPE',
    subCategory: 'ONT',
    unit: 'pcs',
    isSerialized: true,
    purchasePrice: 135000,
    sellingPrice: 220000,
    minimumStock: 5,
  },

  // ─── CAB: Cables (Dropcore per drum & Precon per roll) ─────────────────
  {
    sku: 'EMG-CAB-DRP-1C-1000M',
    name: 'Kabel Dropcore 1 Core 3 Seling 1000m Haspel',
    categoryCode: 'CAB',
    subCategory: 'DRP',
    unit: 'meter',
    isSerialized: true, // Serialized per drum (ROLL-xxx)
    purchasePrice: 750,
    sellingPrice: 1500,
    minimumStock: 1000,
  },
  {
    sku: 'EMG-CAB-PRC-1C-250M',
    name: 'Kabel Precon 1 Core Panjang 250m',
    categoryCode: 'CAB',
    subCategory: 'PRC',
    unit: 'meter',
    isSerialized: true, // Serialized per roll (ROLL-xxx)
    purchasePrice: 220000,
    sellingPrice: 350000,
    minimumStock: 500,
  },
  {
    sku: 'EMG-CAB-PRC-1C-150M',
    name: 'Kabel Precon 1 Core Panjang 150m',
    categoryCode: 'CAB',
    subCategory: 'PRC',
    unit: 'meter',
    isSerialized: true,
    purchasePrice: 140000,
    sellingPrice: 225000,
    minimumStock: 300,
  },
  {
    sku: 'EMG-CAB-UTP-CAT6-305M',
    name: 'Kabel UTP LAN Cat6 305m Box',
    categoryCode: 'CAB',
    subCategory: 'UTP',
    unit: 'box',
    isSerialized: false,
    stockQuantity: 5,
    purchasePrice: 850000,
    sellingPrice: 1100000,
    minimumStock: 2,
  },

  // ─── PAS: Passive Equipment ──────────────────────────────────────────
  {
    sku: 'EMG-PAS-ODP-16P-SOLID',
    name: 'ODP 16 Port Solid Box Kosong',
    categoryCode: 'PAS',
    subCategory: 'ODP',
    unit: 'pcs',
    isSerialized: false,
    stockQuantity: 12,
    purchasePrice: 175000,
    sellingPrice: 275000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-PAS-SPL-1X8-PLC',
    name: 'Splitter Box 1:8 PLC SC/UPC',
    categoryCode: 'PAS',
    subCategory: 'SPL',
    unit: 'pcs',
    isSerialized: false,
    stockQuantity: 25,
    purchasePrice: 65000,
    sellingPrice: 110000,
    minimumStock: 10,
  },

  // ─── CON: Consumables Generic (Quantity-based, isSerialized: false) ────
  {
    sku: 'EMG-CON-TAP-NITTO-BLK',
    name: 'Isolasi Listrik Nitto Hitam',
    categoryCode: 'CON',
    subCategory: 'TAP',
    unit: 'roll',
    isSerialized: false,
    stockQuantity: 40,
    purchasePrice: 12000,
    sellingPrice: 18000,
    minimumStock: 10,
  },
  {
    sku: 'EMG-CON-TIE-30CM-BLK',
    name: 'Kabel Tis 30cm Hitam per Pack (100pcs)',
    categoryCode: 'CON',
    subCategory: 'TIE',
    unit: 'pack',
    isSerialized: false,
    stockQuantity: 30,
    purchasePrice: 22000,
    sellingPrice: 35000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CON-KLM-NO7-WHT',
    name: 'Paku Klem No 7 Putih per Kotak',
    categoryCode: 'CON',
    subCategory: 'kotak',
    isSerialized: false,
    stockQuantity: 50,
    purchasePrice: 8500,
    sellingPrice: 15000,
    minimumStock: 10,
  },
  {
    sku: 'EMG-CON-FOD-60MM-100P',
    name: 'Protection Sleeve / Selongsong 60mm (100pcs)',
    categoryCode: 'CON',
    subCategory: 'FOD',
    unit: 'pack',
    isSerialized: false,
    stockQuantity: 20,
    purchasePrice: 25000,
    sellingPrice: 40000,
    minimumStock: 5,
  },
  {
    sku: 'EMG-CON-PTC-SC-UPC-3M',
    name: 'Patch Cord SC-UPC to SC-UPC 3 Meter',
    categoryCode: 'CON',
    subCategory: 'PTC',
    unit: 'pcs',
    isSerialized: false,
    stockQuantity: 60,
    purchasePrice: 12500,
    sellingPrice: 25000,
    minimumStock: 15,
  },
  {
    sku: 'EMG-CON-PAP-HVS-A4',
    name: 'Kertas HVS A4 75gr per Rim (Dokumen/MOU)',
    categoryCode: 'CON',
    subCategory: 'PAP',
    unit: 'rim',
    isSerialized: false,
    stockQuantity: 10,
    purchasePrice: 48000,
    sellingPrice: 55000,
    minimumStock: 3,
  },

  // ─── MKT: Marketing (isSerialized: false) ──────────────────────────────
  {
    sku: 'EMG-MKT-BRC-PSB-A5',
    name: 'Brosur Pasang Baru Ukuran A5 Glossy',
    categoryCode: 'MKT',
    subCategory: 'BRC',
    unit: 'lembar',
    isSerialized: false,
    stockQuantity: 500,
    purchasePrice: 450,
    sellingPrice: 0,
    minimumStock: 100,
  },
  {
    sku: 'EMG-MKT-STK-ODP-LOGO',
    name: 'Stiker ODP Vinyl Outdoor Logo EMG',
    categoryCode: 'MKT',
    subCategory: 'STK',
    unit: 'lembar',
    isSerialized: false,
    stockQuantity: 200,
    purchasePrice: 1500,
    sellingPrice: 0,
    minimumStock: 50,
  },
];

export async function seedMasterItems() {
  console.log('Seeding EMG Master Items...');
  const createdItems: Record<string, string> = {};

  for (const it of MASTER_ITEMS) {
    const item = await prisma.inventoryItem.upsert({
      where: { sku: it.sku },
      create: {
        sku: it.sku,
        name: it.name,
        categoryCode: it.categoryCode,
        subCategory: it.subCategory,
        unit: it.unit,
        isSerialized: it.isSerialized,
        stockQuantity: it.stockQuantity || 0,
        currentStock: Math.round(it.stockQuantity || 0),
        purchasePrice: it.purchasePrice,
        sellingPrice: it.sellingPrice,
        minimumStock: it.minimumStock,
      },
      update: {
        name: it.name,
        categoryCode: it.categoryCode,
        subCategory: it.subCategory,
        unit: it.unit,
        isSerialized: it.isSerialized,
      },
    });
    createdItems[it.sku] = item.id;
  }

  return createdItems;
}
